data_path: data/dataset.json
feat_type: tfidf # bow, tfidf
model_type: knn
params:
  n_neighbors:
    - 1
    - 2
    - 4
    - 8
    - 12
    - 15
    - 17
    - 20
  weights:
    - uniform
    - distance
  metric:
    - euclidean
    - manhattan
  algorithm:
    - brute