data_path: data/dataset.json
model_name: facebook/bart-large-mnli # joeddav/xlm-roberta-large-xnli, MoritzLaurer/mDeBERTa-v3-base-mnli-xnli, facebook/bart-large-mnli
max_token: 512
exp_type: manual #manual